// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJrJvh24T8r1BfbCm6vP3TfbgsaSYonRI',
    appId: '1:648994476729:web:b1e1208ac9120378e34168',
    messagingSenderId: '648994476729',
    projectId: 'crud-operations-afb1f',
    authDomain: 'crud-operations-afb1f.firebaseapp.com',
    storageBucket: 'crud-operations-afb1f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQlWNhVyYZ7oJDqzeQlKk4fi39m6CvfmQ',
    appId: '1:648994476729:android:fdb2f3e90ec5bf42e34168',
    messagingSenderId: '648994476729',
    projectId: 'crud-operations-afb1f',
    storageBucket: 'crud-operations-afb1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmL_19OJ5yLltVhWvSsicePnhXVIBhNcs',
    appId: '1:648994476729:ios:1901c1bf44641208e34168',
    messagingSenderId: '648994476729',
    projectId: 'crud-operations-afb1f',
    storageBucket: 'crud-operations-afb1f.appspot.com',
    iosBundleId: 'com.example.firebaseCrudoperations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmL_19OJ5yLltVhWvSsicePnhXVIBhNcs',
    appId: '1:648994476729:ios:1901c1bf44641208e34168',
    messagingSenderId: '648994476729',
    projectId: 'crud-operations-afb1f',
    storageBucket: 'crud-operations-afb1f.appspot.com',
    iosBundleId: 'com.example.firebaseCrudoperations',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJrJvh24T8r1BfbCm6vP3TfbgsaSYonRI',
    appId: '1:648994476729:web:8601f99fb753ccace34168',
    messagingSenderId: '648994476729',
    projectId: 'crud-operations-afb1f',
    authDomain: 'crud-operations-afb1f.firebaseapp.com',
    storageBucket: 'crud-operations-afb1f.appspot.com',
  );
}
